import numpy as np

CARDINALITY = {
    "3dshapes": [10, 10, 10, 8, 4, 15],
    "mpi3d": [6, 6, 2, 3, 3, 40, 40],
    "dsprites": [3, 6, 40, 32, 32],
    "cars": [183, 24, 4],
    "isaac": [3, 8, 5, 4, 4, 4, 6, 4, 4],
    "isaac3d": [3, 8, 5, 4, 4, 4, 6, 4, 4],
    "cub": [2,] * 109,
    "ffhq": [2,] * 40,
    "scenes": [2,] * 40,
}
RATIO = {"3dshapes": [1, 1, 1, 2, 1, 5], "dsprites": [1, 2, 8, 8, 8]}

BB_KWARGS = {
    "mpi3d": {"in_channel": 3, "size": 64},
    "isaac": {"in_channel": 3, "size": 128, "f_size": 512},
    "isaac3d": {"in_channel": 3, "size": 128, "f_size": 512},
    "cub": {"in_channel": 3, "size": 256, "f_size": 512},
    "ffhq": {"in_channel": 3, "size": 256, "f_size": 512},
    "scenes": {"in_channel": 3, "size": 256, "f_size": 512},
}

SIZES = {"cub": 256, "isaac": 128, "3dshapes": 64, "mpi3d": 64, "cars": 64}

GENERATOR_KWARGS = {
    "truncation": 0.7,
    "input_is_latent": True,
    "randomize_noise": False,
}

ATTRIBUTES = {
    "ffhq": [
        "5_o_Clock_Shadow",
        "Arched_Eyebrows",
        "Attractive",
        "Bags_Under_Eyes",
        "Bald",
        "Bangs",
        "Big_Lips",
        "Big_Nose",
        "Black_Hair",
        "Blond_Hair",
        "Blurry",
        "Brown_Hair",
        "Bushy_Eyebrows",
        "Chubby",
        "Double_Chin",
        "Eyeglasses",
        "Goatee",
        "Gray_Hair",
        "Heavy_Makeup",
        "High_Cheekbones",
        "Male",
        "Mouth_Slightly_Open",
        "Mustache",
        "Narrow_Eyes",
        "No_Beard",
        "Oval_Face",
        "Pale_Skin",
        "Pointy_Nose",
        "Receding_Hairline",
        "Rosy_Cheeks",
        "Sideburns",
        "Smiling",
        "Straight_Hair",
        "Wavy_Hair",
        "Wearing_Earrings",
        "Wearing_Hat",
        "Wearing_Lipstick",
        "Wearing_Necklace",
        "Wearing_Necktie",
        "Young",
    ],
    "cub": [
        "bill:dagger",
        "bill:all_purpose",
        "bill:cone",
        "tail:rounded",
        "tail:notched",
        "tail:pointed",
        "wing:rounded",
        "wing:pointed",
        "shape:perching",
        "color:brown",
        "color:yellow",
    ],
    "scenes": [
        "dirty",
        "daylight",
        "night",
        "sunrisesunset",
        "dawndusk",
        "sunny",
        "clouds",
        "fog",
        "storm",
        "snow",
        "warm",
        "cold",
        "busy",
        "beautiful",
        "flowers",
        "spring",
        "summer",
        "autumn",
        "winter",
        "glowing",
        "colorful",
        "dull",
        "rugged",
        "midday",
        "dark",
        "bright",
        "dry",
        "moist",
        "windy",
        "rain",
        "ice",
        "cluttered",
        "soothing",
        "stressful",
        "exciting",
        "sentimental",
        "mysterious",
        "boring",
        "gloomy",
        "lush",
    ],
}

IDX2ATTR = {
    "ffhq": np.arange(40),
    "cub": [0, 1, 2, 27, 28, 29, 74, 75, 79, 89, 91],
    "scenes": np.arange(40),
}
